trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - /*
    - /shared/*
    - /test/*
    exclude:
    - README.md
pr:
  autoCancel: false
  branches:
    include:
    - master
  paths:
    include:
    - /*
    - /shared/*
    - /test/*
    exclude:
    - README.md

variables:
  TF_VERSION: '0.11.13' # Terraform version
  TF_VAR_location: 'eastus'
  TF_VAR_company: 'cobalt'


pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    terraform -version
    wget https://releases.hashicorp.com/terraform/$(TF_VERSION)/terraform_$(TF_VERSION)_linux_amd64.zip -q
    unzip -q terraform_$(TF_VERSION)_linux_amd64.zip
    sudo mv terraform /usr/local/bin
    terraform -version
  displayName: 'Install terraform'

- task: AzureCLI@1
  displayName: 'Execute Infratructure Tests'
  inputs:
    azureSubscription: 'JUCOLON Microsoft Azure Internal Consumption (8ff258b7-0b3b-4827-b240-cb8cfab73615)'
    scriptPath: 'tests/main.sh'
    workingDirectory: tests

