trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - /*
    - /shared/*
    - /test/*
    exclude:
    - README.md
pr:
  autoCancel: false
  branches:
    include:
    - master
  paths:
    include:
    - /*
    - /shared/*
    - /test/*
    exclude:
    - README.md

variables:
  TF_VERSION: '0.11.13' # Terraform version

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    terraform -version
    wget https://releases.hashicorp.com/terraform/$(TF_VERSION)/terraform_$(TF_VERSION)_linux_amd64.zip -q
    unzip -q terraform_$(TF_VERSION)_linux_amd64.zip
    sudo mv terraform /usr/local/bin
    terraform -version
  displayName: 'Install terraform'

- task: Bash@3
  inputs:
    targetType: filePath
    filePath: './acr-sp-init-test.sh'
    workingDirectory: test
  displayName: 'Test ACR and SP'
